version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: ["npm", "start"]
  gotify-cleanup:
    build: .
    volumes:
      - ./config.json:/usr/src/app/config.json
    restart: unless-stopped
volumes:
  config: