services:
  gotify-cleanup:
    image: sproove/gotify-cleanup:latest
    container_name: gotify-cleanup
    restart: unless-stopped
    volumes:
      - gotify_cleanup_config:/app/config
volumes:
    gotify_cleanup_config:
      name: gotify_cleanup_config

